### ISSUE TITLE
Frosted Glass stopped working

### ISSUE THREAD

**Issue by prashantmgk** [DiscordStyles/FrostedGlass#10]
![image](https://user-images.githubusercontent.com/30362730/127103683-8688a22d-a52d-47fd-afd5-a0d35cefa7d7.png)
This is the screenshot with the theme on. There is no design applied. Can you please fix it. I really like this theme

**Comment by Kjubbx** [comment]
Same problem

**Comment by Flash08YT** [comment]
The css-file "base.css" is unavailable somehow

**Comment by Flash08YT** [comment]
https://github.com/DiscordStyles/FrostedGlass/issues/6#issuecomment-887185916

**Comment by DanGill** [comment]
I had the same problem

> 
> 
> Fix > [#6 (comment)](https://github.com/DiscordStyles/FrostedGlass/issues/6#issuecomment-887185916)

This worked for me.

**Comment by Kjubbx** [comment]
> Fix > [#6 (comment)](https://github.com/DiscordStyles/FrostedGlass/issues/6#issuecomment-887185916)

Worked, thanks

**Comment by Gibbu** [comment]
Just react with a thumbup. Saying "worked" spams my notifications. 👍

**Comment by Larrasis** [comment]
![image](https://user-images.githubusercontent.com/88050350/127194085-349dc0f3-2e9c-406b-a117-86887df20cf2.png)
i did the fix accordingly and still noting any ideas?

**Comment by emelrad12** [comment]
> ![image](https://user-images.githubusercontent.com/88050350/127194085-349dc0f3-2e9c-406b-a117-86887df20cf2.png)
> i did the fix accordingly and still noting any ideas?

There is no sylvie

**Comment by Gibbu** [comment]
@Larrasis Adding the name of your theme at the end will not work. It **HAS** to be "FrostedGlass.css"
