### ISSUE TITLE
fix your entire code, its fully broken my discord beyond usage and now has destroyed my vencord too. making it unusable. Pls how fix and how go to note pad and delete the link

### ISSUE THREAD

**Issue by dfdfjk34125** [DiscordStyles/FrostedGlass#101]
### Describe the bug
A clear and concise description of what the bug is
nothing visible in settings, servers are broken, dms are broken, this theme is fucking terrible. dont use it
_A clear and concise description of what the bug is_

### To Reproduce

.

### Screenshots

_If applicable, add screenshots to help explain your problem_
![image](https://github.com/DiscordStyles/FrostedGlass/assets/172494789/8de258fb-20bf-4d78-96bc-7008a8e69386)

### Infomation (please complete the following information)

**Discord channel**:  
**OS**: _Windows
**Mod**: vencord
**Discord language**: _Your language_

### Additional context

Pls help me thics fast fix. s My discord died :(

**Comment by Gibbu** [comment]
This isn't my fault, but yours. You've incorrectly imported theme.

**Comment by dfdfjk34125** [comment]
> This isn't my fault, but yours. You've incorrectly imported the theme. `https://discordstyles.github.io/FrostedGlass/dist/FrostedGlass.theme.css` is the correct link.

this real fix or no?
