### ISSUE TITLE
Transparency isn't blurry

### ISSUE THREAD

**Issue by NotDiNozZ** [DiscordStyles/FrostedGlass#13]
Once I set the theme to be transparent and show my background through it, no matter what I set the blur option to, it won't blur it at all.

**Comment by Gibbu** [comment]
That's not how it works. CSS cannot blur anything outside of the window.
For that you'll need something like Glasscord: https://github.com/AryToNeX/Glasscord

But be warned: Glasscord is no longer being actively developed meaning it could contain bugs.
