### ISSUE TITLE
Frosted Glass Transparent Not working August

### ISSUE THREAD

**Issue by ItsJustAlex** [DiscordStyles/FrostedGlass#14]
Better Discord updated and the The frosted glass transparent doesn't work anymore. I have enabled the transparency in the settings and doesn't seem to work.

**Comment by Gibbu** [comment]
Re-eanble the Transparency option.

**Comment by ItsJustAlex** [comment]
I've disabled it and re-enabled and restarted discord it and it still doesn't go transparent.

**Comment by miskaflixazoxy** [comment]
I just reinstalled it, worked for me

**Comment by Gibbu** [comment]
Well, I can't really fix what isn't broken. I'm going to close this issue.
