### ISSUE TITLE
Some UI elements are not properly darkened since recent Discord updates

### ISSUE THREAD

**Issue by RikuKawai** [DiscordStyles/FrostedGlass#2]
First the Audit Log and now the Server List are not being darkened properly.
I'm running Frosted Glass 2.0.8 on Discord Canary c4e4b47 and Powercord v2 83f0aa3.
![image](https://user-images.githubusercontent.com/13458480/112252533-a4245f80-8c33-11eb-9971-2f12c3c71d7f.png) ![image](https://user-images.githubusercontent.com/13458480/112252478-8b1bae80-8c33-11eb-94e1-e1b67bc96a6b.png)

**Comment by Malternative3772** [comment]
Yep. I also run Powercord and I have the same problem

**Comment by Gibbu** [comment]
Ah god damn it. I forgot about the audit log. I'll fix that tomorrow.
