### ISSUE TITLE
Background refreshes after an extended period of time of being minimized

### ISSUE THREAD

**Issue by Hi-ImKyle** [DiscordStyles/FrostedGlass#25]
**Describe the bug**  
After a long period of time, opening discord to the front causes the background image to refetch itself. At first I thought it was just how Electron was handling things but I tried another theme with a background and can't seem to reproduce the issue.

**To Reproduce**  
Have frosted glass enabled, minimize discord for a long time, say an hour(not always an hour, sometimes happens in a lot shorter of a time), and maximize discord. Background should refresh.

**Screenshots**  
Goes from this
![Discord_A9berEt6tZ](https://user-images.githubusercontent.com/25551312/146610753-277f8940-7547-476f-b2e0-88a615264d87.png)
to this
![Discord_qxRJgs4s5i](https://user-images.githubusercontent.com/25551312/146610769-fee23ec2-2ef3-46c3-9f0f-dff21c282c75.png)
then back to the image

**Infomation (please complete the following information):**  
Discord channel: Stable
OS: Windows
Mod: BetterDiscord
Discord language: English

**Additional context**  
I thought it might have been the image I was using since I changed it from the default one and its a larger file, but it seems to do it with the default one too. 

[This theme doesn't appear to do the issue](https://github.com/ClearVision/ClearVision-v6), maybe it is just where the image is being displayed, I see Frosted Glass is on #app-mount, but ClearVision isn't

**Comment by Gibbu** [comment]
Might be fixed in recent updates?

**Comment by Gibbu** [comment]
closed due to inactivity.
