### ISSUE TITLE
Frosted Glass no longer working on Canary 110234 (b3cd76f)

### ISSUE THREAD

**Issue by Lucaskyy** [DiscordStyles/FrostedGlass#27]
**Describe the bug**  
The Frosted Glass theme no longer works on `Canary 110234 (b3cd76f)`.
On the Friends page, everything will be the default dark theme.
In DMs, the "opacity" no longer works, making DMs very bright.

**To Reproduce**  
Update to `Canary 110234 (b3cd76f)` (or higher?), which as of writing the latest Canary version.

**Screenshots**  
Top of channel:
![Img 1](https://i.imgur.com/Xb9eSo5.png)
Channels and (Group) DMs:
![Img 2](https://i.imgur.com/rmyu0r5.png)
Friends tab (censored, obviously):
![Img 3](https://i.imgur.com/OoxvEEh.png)

**Infomation (please complete the following information):**  
Discord channel: Canary  
OS: Windows
Mod: Powercord + GooseMod
Discord language: English

**Comment by Gibbu** [comment]
Correct the newest Cancary version has chnaged a lot of things. And won't be fixed until it comes to Stable.
Discord has a history of updating, reverting, updating, changing in span of a couple of hours to days.

It's pretty much a waste of time to actively support Cancary.
