### ISSUE TITLE
Broken from Canary Update

### ISSUE THREAD

**Issue by SammCheese** [DiscordStyles/FrostedGlass#28]
**Describe the bug**  
Several Elements are not Themed properly in the latest Canary Version

**To Reproduce**  
Start Up Discord

**Screenshots**  
![image](https://user-images.githubusercontent.com/52699291/148661783-8dc96f2a-6e6e-4eaf-8e63-c914b6ac1369.png)

**Infomation (please complete the following information):**  
Discord channel: Canary 
OS: Windows 
Mod: Powercord
Discord language: en_US

**Comment by Gibbu** [comment]
Correct the newest Cancary version has chnaged a lot of things. And won't be fixed until it comes to Stable.
Discord has a history of updating, reverting, updating, changing in span of a couple of hours to days.

It's pretty much a waste of time to actively support Cancary.
