### ISSUE TITLE
background-image-blur does not work when editing "_theme.scss"

### ISSUE THREAD

**Issue by spartaque12** [DiscordStyles/FrostedGlass#29]
background-image-blur does not work when editing "_theme.scss"

STR:

- open FrostedGlass\src\_theme.scss
- edit background-image-blur to 5-10px to see result
- save the file

**Attachments**  
https://streamable.com/9jjqde

**Infomation (please complete the following information):**  
Discord channel: Canary 
OS: *Windows 10 x64 19043*  
Mod: *Powercord*  
Discord language: *en*

**Comment by spartaque12** [comment]
UPD: popout-modal-blur does not work too

**Comment by Gibbu** [comment]
That's because Powercord uses `FrostedGlass\dist\FrostedGlass.theme.css`.
