### ISSUE TITLE
idk what is this

### ISSUE THREAD

**Issue by Miho1254** [DiscordStyles/FrostedGlass#31]
**Describe the bug**  
*i just logged into the discord today and i see this bug*  

**Screenshots**  
*![image](https://user-images.githubusercontent.com/83270073/148864690-c563b549-c89e-486e-90e4-5fbd24781709.png)*  

**Infomation (please complete the following information):**  
Discord channel: *((Stable))*  
OS: *((Windows))*  
Mod: *((BetterDiscord))*  
Discord language: *((Vietnamese))*  

**Additional context**  
*P/s: i editted some stuff in the .css file but today i got this bug?*

**Comment by minijaham** [comment]
Same issue here.
This still happens with the original source

**Comment by Gibbu** [comment]
It was a massive Discord update which *should* hopefully be fixed.
