### ISSUE TITLE
Upwards Offset

### ISSUE THREAD

**Issue by B3rkz** [DiscordStyles/FrostedGlass#41]
### Describe the bug
An offset going up making some buttons not visible

### To Reproduce  
Copy and paste a wall of text and it'll offset it

### Screenshots
*If applicable, add screenshots to help explain your problem*
![image](https://user-images.githubusercontent.com/69863524/174731349-2592bf3c-100f-4f56-ba45-fb2029850f3b.png)

### Infomation (please complete the following information)
**Discord channel**: Stable 
**OS**: Windows
**Mod**: BetterDiscord
**Discord language**: English

**Comment by RisenFalcon** [comment]
duplicate of #35

**Comment by Gibbu** [comment]
Fixed
