### ISSUE TITLE
Screen flickers upon clicking member

### ISSUE THREAD

**Issue by PeachyPieeee** [DiscordStyles/FrostedGlass#42]
### Describe the bug
when clicking some profiles, the screen goes slightly moves and flickers.

### To Reproduce  
i just downloaded this theme. click some profiles on the bottom and it'll move up, and clicking some other profiles will fix it.

### Screenshots
https://user-images.githubusercontent.com/66063309/177791677-640e3b7f-3764-408d-b9bf-181203c41574.MOV

### Infomation
**Discord channel**: *stable*
**OS**: *Windows*
**Mod**: *BetterDiscord*  
**Discord language**: *english*  

### Additional context
my discord isn't chinese. some of my friends just happen to speak chinese. thanks!

**Comment by Gibbu** [comment]
Might be fixed with the recent updates?

**Comment by Gibbu** [comment]
Closed due to inactivity.
