### ISSUE TITLE
the theme doesnt appear in my dc

### ISSUE THREAD

**Issue by amoraselene** [DiscordStyles/FrostedGlass#43]
### Describe the bug
*A clear and concise description of what the bug is*  

### To Reproduce  
*Steps to reproduce the behavior*  

### Screenshots
*If applicable, add screenshots to help explain your problem*

### Infomation (please complete the following information)
**Discord channel**: *Stable/PTB/Canary*  
**OS**: *Windows/Linux/OSX*  
**Mod**: *BetterDiscord/Powercord/GooseMod*  
**Discord language**: *Your language*  

### Additional context
*Add any other context about the problem here. Remove if not applicable.*

**Comment by Gibbu** [comment]
Thanks for that amazingly written bug report.
With this I was able to figure out the exact issue of your problem AND was able to fix every other bug.
Now this theme is perfect. Thank you so much! <3
