### ISSUE TITLE
Forum channels aren't being formatted

### ISSUE THREAD

**Issue by ultraic-space** [DiscordStyles/FrostedGlass#44]
### Describe the bug
Forum channels aren't being formatted.

### To Reproduce  
1. Use the Frosted Glass Theme
2. Enter a forum channel

### Screenshots
![image](https://user-images.githubusercontent.com/108235651/184158795-27c68b5f-e215-4553-9460-07fcdd76f3e9.png)
![image](https://user-images.githubusercontent.com/108235651/184159088-9ae61f98-0251-454a-a579-2b1fdc7b5efc.png)

### Infomation (please complete the following information)
**Discord channel**: *Stable*
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English (US)*

**Comment by JimDude7404** [comment]
Same here on MacOS

**Comment by Gibbu** [comment]
Fixed
