### ISSUE TITLE
User Profile Popouts are Transparent

### ISSUE THREAD

**Issue by SyonaR** [DiscordStyles/FrostedGlass#46]
Whenever a user is clicked on, their profile popouts are transparent. This randomly started within the last week, and I can't find anything in the settings to fix it. Here is an example: 
![image](https://user-images.githubusercontent.com/81336988/192194590-9f5726d8-83f1-41c5-8932-d146268ddddc.png)

**Comment by Gibbu** [comment]
Fixed.
