### ISSUE TITLE
Laggy UI

### ISSUE THREAD

**Issue by SyonaR** [DiscordStyles/FrostedGlass#47]
After the recent fix involving transparent profile popouts, the theme UI is pretty laggy on every interaction. I tried reloading, as well as redownloading and enabling it, to no avail.

**Comment by Gibbu** [comment]
Make sure Hardware Acceleration is enabled in your Advanced Discord settings

**Comment by SyonaR** [comment]
Will do. I saw that the new Discord update has broken Better Discord for
the time being anyways. Thank you!

**Comment by Bastianexe4** [comment]
I had the same issue, for fix it I just deleted the line 216 and 217 in the FrostedGlass.css
Those lines of code are:

  -webkit-backdrop-filter: blur(var(--background-image-blur));
          backdrop-filter: blur(var(--background-image-blur));

I don't know what it could be but the lag drop almost to 0

**Comment by hleokixxs** [comment]
> I had the same issue, for fix it I just deleted the line 216 and 217 in the FrostedGlass.css Those lines of code are:
> 
> -webkit-backdrop-filter: blur(var(--background-image-blur)); backdrop-filter: blur(var(--background-image-blur));

how would you edit the file tho, isnt it imported from the site? would i just save it myself and edit it there?

**Comment by Bastianexe4** [comment]
Yeah, I just copy all of the code and pasted it on the .css file, then deleted the @import.

**Comment by Gibbu** [comment]
I *finally* added a `--background-blur-visiblity` variable that, when set to `none` will completely disable the blur effect.
As a sort of replacement, you can use this:
```css
#app-mount .bg-1QIAus {
	filter: blur(10px);
}
```
This will blur the entire image, not just the area of the app.

Sorry it took me forever to reply to this, been busy with other things and I find working on this theme very boring.
