### ISSUE TITLE
Various differences in blur, shading, or tinting

### ISSUE THREAD

**Issue by Kuuuube** [DiscordStyles/FrostedGlass#48]
### Describe the bug

The most recent updates have made some things look much brighter without any changes to my settings.

### To Reproduce

The way I compared back to the old version of the theme was throwing the old theme from your deploy branch into my custom css while using an invalid import url in the theme settings file. To go back to the new version I removed the custom css and fixed the import url in the theme settings file.

If it helps here is my settings file (renamed to txt for upload): [FrostedGlass.theme.css.txt](https://github.com/DiscordStyles/FrostedGlass/files/9656911/FrostedGlass.theme.css.txt)

### Screenshots

Here's a few examples of what it looks like before and after the recent updates:

Before:
![message_old](https://user-images.githubusercontent.com/61125188/192554378-77f41389-88f5-4fa3-839c-dca992f595c2.PNG)

After:
![message_new](https://user-images.githubusercontent.com/61125188/192554397-34a71583-bee1-4479-ab13-c6f449ad3aab.PNG)

Before:
![user_old](https://user-images.githubusercontent.com/61125188/192554434-0eccfdde-1679-4f6f-b8da-476d1845b493.PNG)

After:
![user_new](https://user-images.githubusercontent.com/61125188/192554472-386fb415-8dd1-4421-946c-4faedc23a948.PNG)

Before:
![right_click_old](https://user-images.githubusercontent.com/61125188/192554505-76387f4a-166d-4935-b33c-9379173d5604.PNG)

After:
![right_click_new](https://user-images.githubusercontent.com/61125188/192554532-e3e1a0a0-79fb-4d50-904a-313e4be33026.PNG)

### Infomation (please complete the following information)

**Discord channel**: _Stable_  
**OS**: _Windows_  
**Mod**: _BetterDiscord_  
**Discord language**: _English_

**Comment by davidc1701** [comment]
I've also noticed that the variable --popout-modal-brightness doesn't seem to change anything that I can see, and besides the popups mentioned above, the one you get when you right click a forum post (to say, easily follow a post or add tags) is, at least with my current background, too bright and I could not find a way to change how this appears.
![image](https://user-images.githubusercontent.com/48530408/192585391-19430371-5a19-4a6a-919a-7a3d53eb1152.png)

**Comment by Kuuuube** [comment]
> I've also noticed that the variable --popout-modal-brightness doesn't seem to change anything that I can see, and besides the popups mentioned above, the one you get when you right click a forum post (to say, easily follow a post or add tags) is, at least with my current background, too bright and I could not find a way to change how this appears.

To add to this I also noticed that in the deploy branch those variables were changed along but even the updated ones don't work <https://github.com/DiscordStyles/FrostedGlass/blob/114fcf9f5bfe9849e7b1bfc18a73a6bc0cfacb3c/FrostedGlass.theme.css#L28-L31> <https://github.com/DiscordStyles/FrostedGlass/blob/114fcf9f5bfe9849e7b1bfc18a73a6bc0cfacb3c/FrostedGlass.theme.css#L52>

**Comment by Gibbu** [comment]
I must've set something up incorrectly as it should just work.
I'll take a look later today.

**Comment by AzureShark** [comment]
To further add to this, the variables for tint (--tint-colour and --tint-brightness) are currently having no effect.
![owFbRNW 1](https://user-images.githubusercontent.com/20551944/192903539-d066d701-0922-4239-8fd7-aaf6e91fcdd9.png)
![Diq7lEo 1](https://user-images.githubusercontent.com/20551944/192903573-314e90bf-0b74-4afd-9591-973d2566a15a.png)
Hope this helps!

**Comment by Gibbu** [comment]
@Kuuuube Can you share your `.theme.css` file?

**Comment by Gibbu** [comment]
GitHub I didn't say close it!

**Comment by AzureShark** [comment]
Can confirm that tinting and pop-out variables appear to be fixed!

**Comment by Kuuuube** [comment]
> It should've been fixed.

Everything seems to be fixed now as far as i can tell except the popout when clicking on someone's name. Both on the right sidebar or above a message.

**Comment by MentalMasochist** [comment]
hey popout-modal-brightness is still not doing anything for me

**Comment by Gibbu** [comment]
Repalce `--popout-modal-brightness` with `overlay-brightness`

**Comment by Kuuuube** [comment]
Closing as this appears to be completely fixed. I can't find any areas where it's broken anymore.
