### ISSUE TITLE
Status selector is unthemed

### ISSUE THREAD

**Issue by uetori** [DiscordStyles/FrostedGlass#49]
### Describe the bug

status selector is not themed

### To Reproduce

Click your profile icon in the bottom left, when it pops up the status selector will be black and unthemed

### Screenshots

![image](https://user-images.githubusercontent.com/97866817/193438585-95999486-1703-40aa-ae4a-cfebc7e18095.png)

### Infomation (please complete the following information)

**Discord channel**: Stable 
**OS**: Windows 10 21H1
**Mod**: BetterDiscord  
**Discord language**: English

**Comment by Gibbu** [comment]
Fixed.
