### ISSUE TITLE
Theme bug

### ISSUE THREAD

**Issue by Soulivan71** [DiscordStyles/FrostedGlass#51]
### To Reproduce
Turn on theme just transparent

### Screenshots
https://cdn.discordapp.com/attachments/1071916250239860906/1071916778428563456/image.png

### Infomation (please complete the following information)

Ptb 172007 (3957068) Host 1.0.1023 (29127) Windows 10 64-Bit (10.0.19045)

**Comment by Gibbu** [comment]
Just re-enable the "Enable Transparency" option in BetterDiscord settings.

**Comment by Soulivan71** [comment]
This appeard like this 
![image](https://user-images.githubusercontent.com/36502190/222500135-0244cc75-3590-4105-8dd1-6eca606d9ffb.png)

**Comment by Soulivan71** [comment]
Mb Im using a file that someone else send me to just have the background transparent and not changing anything else.
So its not ur
