### ISSUE TITLE
Server List Background and Scrollbar

### ISSUE THREAD

**Issue by Itaxhix** [DiscordStyles/FrostedGlass#52]
Discord has changed the .scrollerBase ID of the guild column from "_bVAAt" to "1Pkza4", this causes the scrollbar to be visible in the server list and also affects the background of the server list itself. (Background bug very noticeable with dark background image)

### Solution:
src/theme/app/_background.scss (Line 38): _bVAAt -> 1Pkza4
src/theme/guilds/_container.scss (Line 3): _bVAAt -> 1Pkza4

### Solution for users with the already compiled css: (in case this doesn't get fixed yet)
Copy [this](https://discordstyles.github.io/FrostedGlass/dist/FrostedGlass.css) into Notepad++ or something
There's a _bVAAt in Lines 262, 478 and 481; replace them with 1Pkza4
Upload the css somewhere and replace the first import link in your theme's css

**Comment by xXCannYXx** [comment]
can you upload the fixed one? cause i have no idea what to do i copied your text and discord sad frosted class is outdated

**Comment by xXCannYXx** [comment]
and for css?

**Comment by xXCannYXx** [comment]
idk how i do that for css i changed the lines you sad and copied it into my css theme like you sad but discord still says outdated

**Comment by macluxHD** [comment]
For now you can fix it using the file in my fork, to do that just replace the url in the first import.

`@import url("https://macluxhd.github.io/FrostedGlass/dist/FrostedGlass.css");`

Switch it back to the old url when the fix has actually been merged to this repo though

`@import url("https://discordstyles.github.io/FrostedGlass/dist/FrostedGlass.css");`
