### ISSUE TITLE
fix your entire code, its fully broken my discord beyond usage and now has destroyed my vencord too. making it unusable.

### ISSUE THREAD

**Issue by pancakes111213123432453254235** [DiscordStyles/FrostedGlass#58]
### Describe the bug

_A clear and concise description of what the bug is_
nothing visible in settings, servers are broken, dms are broken, this theme is fucking terrible. dont use it
### To Reproduce

_Steps to reproduce the behavior_

### Screenshots

_If applicable, add screenshots to help explain your problem_

### Infomation (please complete the following information)

**Discord channel**: _Stable/PTB/Canary_  
**OS**: _Windows 
**Mod**: _BetterDiscord/Powercord/GooseMod_  
**Discord language**: _Your language_

### Additional context

_Add any other context about the problem here. Remove if not applicable._

**Comment by Gibbu** [comment]
Thanks for that very detailed bug report!  
With all this information I am sure to fix all the bugs you've pointed out! 👍👍👍

**Comment by fowlis** [comment]
This isn't an issue with the theme. You probably just inserted it wrong.

![image](https://files.catbox.moe/mz2b2s.jpg)
![image2](https://files.catbox.moe/jgwk2z.jpg)

**Comment by Gibbu** [comment]
They 100% did, as has many others. I've updated all my readme files to display the **CORRECT** link for Vencord.

**Comment by IcecreamOwO** [comment]
ok so i inserted it wrong like u said but like any idea how i could fix vencord or discord it just says 
![image](https://user-images.githubusercontent.com/131265526/233073757-18e3d9f1-dff0-4721-b1d9-2e9640f525d7.png)

**Comment by IcecreamOwO** [comment]
nvm figured it out had to go to note pad and delete the link
