### ISSUE TITLE
heavy window

### ISSUE THREAD

**Issue by RealSourceOfficial** [DiscordStyles/FrostedGlass#61]
### Describe the bug
The window can't be moved

### To Reproduce
Use FrostedGlass    
Try to move the window

### Infomation (please complete the following information)

**Discord channel**: Stable/ 
**OS**: Windows
**Mod**: BetterDiscord 
**Discord language**: English

**Comment by RealSourceOfficial** [comment]
Update: this seems to be a very obscure issue with the title bar, but dragging from the search bar can move the window. However, the window is not auto-sized at all

**Comment by Gibbu** [comment]
You have plenty of room to play with. I've tested this on multiple themes and all work just fine.
Example:

https://github.com/DiscordStyles/FrostedGlass/assets/20338746/6fd9c5cd-7ac7-40c1-b003-7b9f38d37636

But if you wish, you can add:
```css
:root {
  --TB-bar-height: 15px;
}
```
To increase the height to make it easier to grab.
