### ISSUE TITLE
Discord PTB make your theme broken again

### ISSUE THREAD

**Issue by Miho1254** [DiscordStyles/FrostedGlass#69]
### Describe the bug

The background image hidden by default discord darkmode color

### To Reproduce

IDK

### Screenshots

![image](https://github.com/DiscordStyles/FrostedGlass/assets/83270073/b7b0c76b-6b26-4ec4-91c7-542673c6c8f9)
### Infomation (please complete the following information)
![image](https://github.com/DiscordStyles/FrostedGlass/assets/83270073/e91f7edc-650d-4e6f-8b21-21c3c837a31f)

**Discord channel**: PTB
**OS**: _Windows
**Mod**: OpenAsar  
**Discord language**: Vietnamese

### Additional context

btw, i just edited some css to make the window padding become 0px because i like it, but i swear it's not the problem

**Comment by Gibbu** [comment]
It's because you have a Discord Nitro theme enabled.

**Comment by Miho1254** [comment]
> It's because you have a Discord Nitro theme enabled.

Lmao, i almost forgot

**Comment by Gibbu** [comment]
Clearly you did forget. I assume the issue is fixed?
