### ISSUE TITLE
annoying window frame

### ISSUE THREAD

**Issue by MrChallenge** [DiscordStyles/FrostedGlass#72]
I don't know where you can leave an application to improve theme, so I write bug reports (sorry)

I'm annoyed by distance around application window, I hate fact that background image makes window lighter at edges than in middle, so I changed value in "--window-padding" parameter to 0px. I think it's better than before. If you don't care about this offer you can ignore it, I just wanted to let you know. If someone doesn't like it either, then I think... I hope he deals with it the same way I did.

**Comment by Gibbu** [comment]
I don't understand this. You fixed your "issue" by using the variables provided by the theme.
