### ISSUE TITLE
BDA Incorrect CDNJS preview link

### ISSUE THREAD

**Issue by Ambushfall** [DiscordStyles/FrostedGlass#74]
### Describe the issue.

Link is [FrostedGlass.theme.css](https://cdn.jsdelivr.net/gh/DiscordStyles/FrostedGlass/dist/FrostedGlass.theme.css)

Should be [FrostedGlass.css](https://cdn.jsdelivr.net/gh/DiscordStyles/FrostedGlass@deploy/dist/FrostedGlass.css)

Cheers!

**Comment by Gibbu** [comment]
Fixed 👍
