### ISSUE TITLE
Popout modal brightness not working

### ISSUE THREAD

**Issue by Itaxhix** [DiscordStyles/FrostedGlass#78]
`--popout-modal-brightness` does not change the user/profile popout brightness.

In line 60 of **"theme/app/_background.scss"**, the box-shadow value is:
`inset 0 0 0 100vmax rgb(0, 0, 0, var(--overlay-brightness, var(--popout-modal-brightness)))`

Apparently that doesn't affect the brightness because line 17 of **"theme/popouts/_userpopout.scss"** has a different box-shadow value of:
`inset 0 0 0 100vmax rgb(0, 0, 0, var(--overlay-brightness))`

After changing line 17 to include `--popout-modal-brightness`, the popout brightness works again.

**Comment by Gibbu** [comment]
That's because the BD website hasn't got the most updated theme file. Either download it from the GitHub repo or use https://bdeditor.dev
