### ISSUE TITLE
Freezes in QTile WM when closing a window that it's tiled with

### ISSUE THREAD

**Issue by KSPAtlas** [DiscordStyles/FrostedGlass#8]
I'm not sure if this happens on other Linux tiling WMs, but on QTile it freezes. Does not happne with any other theme.

**Comment by Gibbu** [comment]
Ahhhhh. What?

**Comment by KSPAtlas** [comment]
If you want to test this out, start a VM with Linux (any distribution will do, as long as it has Qtile). Then, install Qtile and log into it. Install Discord then apply the theme and you'll see the issue

**Comment by KSPAtlas** [comment]
I might give some evidence but I don't have my computer on rn

**Comment by Gibbu** [comment]
I'm sorry, I'm not going through all that just to fix it for 1 person.

**Comment by KSPAtlas** [comment]
While it may be only for one person now, imagine how many more people will have this same issue when this theme gets more popular. Also, it's never good to have buggy code unless it's a developer release

**Comment by Gibbu** [comment]
> it's never good to have buggy code unless it's a developer release.

You're the only person that I've heard to have this problem.
As I said, I'm not doing all that to fix it for 1 person.

Either fix it yourself and then tell me what you did or find another theme.

**Comment by KSPAtlas** [comment]
I can't really fix it myself because I don't know CSS well. I think it might be a bug in the Better-discord rendering engine
