### ISSUE TITLE
No Transparency

### ISSUE THREAD

**Issue by dbgoodm** [DiscordStyles/FrostedGlass#97]
### Describe the bug

There is no transparency with the theme even with it enabled through Vencord

### To Reproduce

N/A

### Screenshots

![Discord_iy89zielSJ](https://github.com/DiscordStyles/FrostedGlass/assets/37591100/c83671c8-b7a8-4ac2-964b-546f19ab7e57)
![Discord_LUrgt6g2jA](https://github.com/DiscordStyles/FrostedGlass/assets/37591100/41c0eb20-b73a-4fd3-8641-2dba380e3b5f)

### Infomation (please complete the following information)

**Discord channel**: Stable
**OS**: _Windows
**Mod**: Vencord
**Discord language**: English

**Comment by Gibbu** [comment]
Wrong theme

**Comment by dbgoodm** [comment]
I tried it with and without darkmatter still not transparency... So what am I missing?
